(6-2)中級 従業員曖昧検索
tarayama/ex-emp-management-bugfix pull request #13
Opened 2022-06-10 01:44 UTC by tarayama

従業員あいまい検索機能を実装しました。

### 実装内容
- フォーム等を実装
- 検索結果が0件の際に「検索結果：0件」と表示。  また、それ以外の時でも検索件数が表示できるように対応しました。
- 実装したフォーム等についてbootstrapで装飾しました。  

レビューをよろしくお願いいたします

2022-06-10 06:30 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-06-10 06:30 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/EmployeeController.java
> +	}
今後のページング処理をシンプルにするために、Controllerにおいて一覧表示を行うshowListメソッドと、曖昧検索を行うメソッドを統合しましょう。

2022-06-10 06:30 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/EmployeeController.java
> +	}
○今の状態だと以下の仕様が全部満たされてていないように思います。
　テストをお願いします。満たされていない場合は修正をお願いします。満たされている場合は無視してください。
　　仕様
　　・空文字で検索した場合
　　　→全件検索結果を表示させる
　　・指定した文字列が存在しなかった場合
　　　→「１件もありませんでした」というメッセージと共に全件検索結果を表示させる
　　※ユーザの使いやすさを考えた結果このような仕様にしました

2022-06-10 06:37 UTC, tarayama commented on src/main/java/jp/co/sample/emp_management/controller/EmployeeController.java
> +	}
> 指定した文字列が存在しなかった場合「１件もありませんでした」と表示させる。

このことについてなのですが、検索結果：０件にすれば理解できると思いこのように実装しました。
１件もありませんでしたについても実装するべきでしょうか？

2022-06-10 06:44 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/EmployeeController.java
> +	}
はい。要望通り「１件もありませんでした」と表示させて欲しいです。

2022-06-10 06:45 UTC, tarayama commented on src/main/java/jp/co/sample/emp_management/controller/EmployeeController.java
> +	}
承知しました。そのように対応します。

2022-06-10 07:29 UTC, tarayama commented
Controllerにおいて一覧表示を行うshowListメソッドと、曖昧検索を行うメソッドの統合と０件の際のメッセージについて追加実装しました。

再度レビューをよろしくお願いいたします。

2022-06-12 23:32 UTC, igamasayuki approved these changes
問題ありませんので承認いたします。

気になる点をコメントしました。
承認しますが、次回以降意識していただきますようお願い致します。

2022-06-12 23:32 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/service/EmployeeService.java
> +
JavaDocコメントを記述しましょう。

2022-06-12 23:32 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/repository/EmployeeRepository.java
> +	public List<Employee> findByName(String name){
JavaDocコメントを記述しましょう。

2022-06-12 23:32 UTC, merged