(5-3)上級 パスワード暗号化orハッシュ化,
tarayama/ex-emp-management-bugfix pull request #14
Opened 2022-06-10 06:25 UTC by tarayama

2022-06-10 06:38 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-06-10 06:38 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/common/WebSecurityConfig.java
> +    }
※この処理がBCryptPasswordEncoderをDIコンテナに登録している処理となります。

2022-06-10 06:38 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/AdministratorController.java
> +		BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();
ここではBCryptPasswordEncoderをインスタンス化しても良いのですが、せっかくBCryptPasswordEncoderをDIコンテナに登録しているため、DIして持ってきましょう。

2022-06-10 06:38 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/AdministratorController.java
> -		BeanUtils.copyProperties(form, administrator);
BeanUtils.copyProperties(form, administrator);は復活させてください。

2022-06-10 06:38 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/AdministratorController.java
> +		administrator.setPassword(encoder.encode(form.getPassword()));
ハッシュ化処理はServiceの中で行いましょう。

2022-06-10 06:38 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/EmployeeController.java
> +
良く調べられましたね！このやり方は私も知りませんでした！

2022-06-10 06:38 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/common/WebSecurityConfig.java
> +@EnableWebSecurity
もしかしたらこの行はなくても動くかもしれません。

2022-06-10 06:38 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/common/WebSecurityConfig.java
> +	private AdministratorService userDetailsService;
もしかしたらこの行はなくても動くかもしれません。

2022-06-10 06:38 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/common/WebSecurityConfig.java
> +    }
もしかしたらこの行はなくても動くかもしれません。

2022-06-10 07:05 UTC, tarayama commented
上記に挙げられていた不要かもしれないものをすべて試し、いるもののみ残しました。

また、BeanUtileプロパティとエンコードのserviceクラスへの移動も実装しました。

再度レビューをよろしくお願いいたします。

2022-06-12 23:34 UTC, igamasayuki approved these changes
とてもわかりやすくなったと思います。
承認します。

2022-06-12 23:34 UTC, merged