(1-3)中級 Eメール重複チェック
tarayama/ex-emp-management-bugfix pull request #7
Opened 2022-06-09 07:08 UTC by tarayama

Eメールの重複チェック機能を実装しました。
Emailの入力フォームのフォーカスが外れた時に非同期でチェックを行い、メッセージを挿入しています。

レビューをよろしくお願いいたします。

2022-06-09 10:11 UTC, igamasayuki requested changes
　こちらの処理ですが、jQueryを使用した場合でも、登録ボタンを押された際に
　サーバー側でもチェックを行うようにしてください。
　(jQueryを使用していても良いですが、必ずサーバー側でもチェックが必要です。
　理由：ブラウザでJavaScriptを無効にしていた場合でもチェックできるため)

差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-06-09 10:11 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/service/AdministratorService.java
> +	}
このメソッド良いです！

2022-06-10 00:26 UTC, tarayama commented
サーバー側でのメールアドレスの重複チェックを実装しました。

再度レビューをよろしくお願いいたします

2022-06-10 00:58 UTC, igamasayuki approved these changes
問題ありませんので承認いたします。
プルリクやコミットの粒度がとてもわかりやすいです。

2022-06-10 00:58 UTC, merged